language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction

env:
  - APP_KEY='base64:BIhG4QeNiijhPOV3I8cfvDMug/HvfWJZRujRGJxlCCU='
  - DB_CONNECTION=sqlite
  - DB_DATABASE=':memory:'
